# Generated by Django 4.2.10 on 2024-03-02 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namegroup', models.CharField(max_length=255, verbose_name='название_группы')),
            ],
            options={
                'verbose_name': 'Group группа',
                'verbose_name_plural': 'Group группы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameless', models.CharField(max_length=255, verbose_name='название_урока')),
            ],
            options={
                'verbose_name': 'Lesson урок',
                'verbose_name_plural': 'Lesson уроки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameprod', models.CharField(max_length=255, verbose_name='название_продукта')),
                ('datestart', models.DateTimeField(blank=True, null=True, verbose_name='дата_начала')),
                ('price', models.FloatField(default=0.0, verbose_name='стоимость')),
                ('kolvomin', models.IntegerField(default=1, verbose_name='наим_колво_в_группе')),
                ('kolvomax', models.IntegerField(default=1, verbose_name='наиб_колво_в_группе')),
            ],
            options={
                'verbose_name': 'Product курс',
                'verbose_name_plural': 'Product курсы',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.FileField(unique=True, upload_to='video/', verbose_name='ссылка_на_видео')),
            ],
            options={
                'verbose_name': 'Videos видео',
                'verbose_name_plural': 'Videos видевы',
            },
        ),
        migrations.CreateModel(
            name='VideosLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appshkolle.lesson')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appshkolle.videos')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appshkolle.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProduct набор_на_курс',
                'verbose_name_plural': 'UserProduct наборы_на_курсы',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appshkolle.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserGroup набор_в_группу',
                'verbose_name_plural': 'UserGroup наборы_в_группы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(through='appshkolle.UserProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='videos',
            field=models.ManyToManyField(through='appshkolle.VideosLesson', to='appshkolle.videos'),
        ),
        migrations.AddField(
            model_name='group',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appshkolle.product'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(through='appshkolle.UserGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author преподаватель',
                'verbose_name_plural': 'Author преподаватели',
            },
        ),
    ]
