# Generated by Django 4.2.10 on 2024-03-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshkolle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nameavtor',
            field=models.CharField(max_length=255, null=True, verbose_name='препод'),
        ),
    ]
