# Generated by Django 4.2.10 on 2024-03-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshkolle', '0002_author_nameavtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nameavtor',
            field=models.CharField(max_length=255, verbose_name='препод'),
        ),
    ]
