# Generated by Django 4.2.10 on 2024-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshkolle', '0003_alter_author_nameavtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='продукт заполнен'),
        ),
    ]
