# Generated by Django 4.2.10 on 2024-03-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshkolle', '0004_product_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, verbose_name='продукт заполнен'),
        ),
    ]
